# Do NOT update manually; changes here will be overwritten by Copier
_commit: 3a7882d
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_real_version: 16.0
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: ''
repo_name: ' Extra modules to import data in odoo'
repo_slug: grap-odoo-import
repo_website: https://github.com/grap/grap-odoo-import
use_pyproject_toml: false
use_ruff: false

